#:schema https://starship.rs/config-schema.json

add_newline = false

[cmd_duration]
format = "[$duration]($style) "
style = "bold dimmed white"

[git_branch]
format = "[$branch(:$remote_branch)]($style) "

[git_status]
format = "([$all_status$ahead_behind]($style) )"

[container]
disabled = true

[hostname]
disabled = true

[line_break]
disabled = true

[package]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[username]
disabled = true
