#:schema https://starship.rs/config-schema.json

add_newline = false

[cmd_duration]
format = "[$duration]($style) "
style = "bold dimmed white"

[git_branch]
symbol = ""

[git_status]
format = "([$all_status$ahead_behind]($style) )"

[line_break]
disabled = true

[package]
disabled = true

[python]
disabled = true

[rust]
disabled = true
