"attribute" = "base0A"
"comment" = "base0F"
"constant" = "base09"
"constant.character" = "base0C"
"constant.character.escape" = "base0E"
"constructor" = "base0D"
"function" = "base0D"
"function.macro" = "base09"
"keyword" = "base0E"
"label" = "base0C"
"namespace" = "base0A"
"operator" = "base0D"
"punctuation" = "base04"
"punctuation.special" = "base0D"
"special" = "base0D"
"string" = "base0B"
"string.regexp" = "base0E"
"string.special" = "base0D"
"string.special.symbol" = "base08"
"tag" = "base0D"
"type" = "base0A"
"type.builtin" = "base0E"
"type.enum.variant" = "base0C"
"variable" = "base05"
"variable.builtin" = "base08"
"variable.other.member" = "base0D"

"markup.bold" = { modifiers = ["bold"] }
"markup.heading.1" = "base08"
"markup.heading.2" = "base09"
"markup.heading.3" = "base0A"
"markup.heading.4" = "base0B"
"markup.heading.5" = "base0D"
"markup.heading.6" = "base0C"
"markup.italic" = { modifiers = ["italic"] }
"markup.link.label" = "base0D"
"markup.link.text" = "base0C"
"markup.link.url" = { fg = "base0D", underline = { style = "line" } }
"markup.list" = "base09"
"markup.list.checked" = "base0B"
"markup.list.unchecked" = "base04"
"markup.quote" = "base04"
"markup.raw" = "base04"
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"error" = "base08"
"hint" = "base0C"
"info" = "base0D"
"warning" = "base0A"

"diagnostic" = { underline = { color = "base0D", style = "curl" } }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"diagnostic.error" = { underline = { color = "base08", style = "curl" } }
"diagnostic.hint" = { underline = { color = "base0C", style = "curl" } }
"diagnostic.info" = { underline = { color = "base0D", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.warning" = { underline = { color = "base0A", style = "curl" } }

"diff.delta" = "base0D"
"diff.minus" = "base08"
"diff.plus" = "base0B"

"ui.background" = { bg = "base00" }
"ui.bufferline" = { fg = "base04", bg = "base01" }
"ui.bufferline.active" = { fg = "base04", bg = "base00" }
"ui.bufferline.background" = { bg = "base01" }
"ui.cursor" = { fg = "base00", bg = "base04" }
"ui.cursor.match" = { fg = "base09", modifiers = ["bold"] }
"ui.cursor.primary" = { fg = "base00", bg = "base05" }
"ui.cursor.select" = { fg = "base01", bg = "base04" }
"ui.gutter" = { bg = "base00" }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.linenr" = { fg = "base03", bg = "base00" }
"ui.linenr.selected" = { fg = "base03", bg = "base00" }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.scroll" = { fg = "base03", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04", modifiers = ["bold"] }
"ui.popup" = { bg = "base01" }
"ui.selection" = { bg = "base02" }
"ui.selection.primary" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.statusline.inactive" = { fg = "base03", bg = "base01" }
"ui.statusline.insert" = { fg = "base0B", bg = "base01" }
"ui.statusline.normal" = { fg = "base04", bg = "base01" }
"ui.statusline.select" = { fg = "base0A", bg = "base01" }
"ui.text" = "base05"
"ui.text.directory" = "base0D"
"ui.text.focus" = { fg = "base05", modifiers = ["bold"] }
"ui.text.inactive" = "base03"
"ui.virtual" = "base04"
"ui.virtual.indent-guide" = "base03"
"ui.virtual.inlay-hint" = "base03"
"ui.virtual.jump-label" = { fg = "base0A", modifiers = ["bold"] }
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.whitespace" = "base02"
"ui.virtual.wrap" = "base02"
"ui.window" = "base02"

[palette]
base00 = "#151515"
base01 = "#202020"
base02 = "#303030"
base03 = "#505050"
base04 = "#b0b0b0"
base05 = "#d0d0d0"
base06 = "#e0e0e0"
base07 = "#f5f5f5"
base08 = "#cc6666"
base09 = "#de935f"
base0A = "#f0c674"
base0B = "#b5bd68"
base0C = "#8abeb7"
base0D = "#81a2be"
base0E = "#b294bb"
base0F = "#c97b8a"
